#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';

function calculateExpression(string $expression): int
{
    [$firstNumber, $operation, $secondNumber] = explode(" ", $expression);
    if ($operation === "+") {
        return (int)$firstNumber + (int)$secondNumber;
    } elseif ($operation === "-") {
        return (int)$firstNumber - (int)$secondNumber;
    } elseif ($operation === "*") {
        return (int)$firstNumber * (int)$secondNumber;
    }
    return 0;
}

function calcGame(): array
{
    $firstNumber = rand(0, 100);
    $operation = ["+", "-", "*"][rand(0, 2)];
    $secondNumber = rand(0, 100);
    $question = "{$firstNumber} {$operation} {$secondNumber}";
    $correctAnswer = (string)calculateExpression($question);
    return [$question, $correctAnswer];
}

main("calc");
