#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';

function isEven(int $number): string
{
    if ($number % 2 === 0) {
        return "yes";
    }
    return "no";
}

function evenGame(): array
{
    $question = rand(0, 100);
    $correctAnswer = isEven($question);
    return [$question, $correctAnswer];
}

main("even");
