#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';

function isPrime(int $number): string
{
    for ($i = 2; $i < $number - 1; $i++) {
        if ($number % $i === 0) {
            return "no";
        }
    }
    return "yes";
}

function primeGame(): array
{
    $number = rand(0, 100);
    $question = $number;
    $correctAnswer = isPrime($number);
    return [$question, $correctAnswer];
}

main("prime");
