#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';

function getProgression(int $startNumber, int $step, int $length, int $missingIndex): array
{
    $progression = [];
    for ($i = 0; $i < $length; $i++) {
        $progression[] = $startNumber;
        $startNumber += $step;
    }
    $correctAnswer = (string)$progression[$missingIndex];
    $progression[$missingIndex] = "...";
    return [implode(" ", $progression), $correctAnswer];
}

function progressionGame(): array
{
    $startNumber = rand(0, 50);
    $step = rand(1, 10);
    $length = rand(9, 11);
    $missingIndex = rand(0, $length - 1);
    return getProgression($startNumber, $step, $length, $missingIndex);
}

main("progression");
